name: ecommerce_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  persistent_bottom_nav_bar_v2: ^4.2.3
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
